config/routes.rb
Rails.application.routes.draw do

  root 'pages#home' 
  get  'about', to: 'pages#about'
  resources :articles

  get 'signup', to: 'users#new'
  resources 'users', except:[:new]

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to(:user)
	validates :title ,presence: true 
	validates :description ,presence: true, length:{ minimum: 3}
	validates :user_id , presence: true
end

app/models/user.rb
class User < ActiveRecord::Base

	has_many(:articles)
	before_save { self.email = email.downcase } 

	validates :username , presence: true, 
						uniqueness: {case_sensitive: false}, 
						length: {minimum: 3}

	VALID_EMAIL_REGEX =  /\A[\w+\.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email , presence: true , 
						uniqueness: {case_sensitive: false},
						length: {minimum: 3},
						format: {with:VALID_EMAIL_REGEX}

	has_secure_password
	

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :get_article, only: [:edit, :update, :show, :destroy]

  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    # debugger
    # render plain: params.inspect
    @article = Article.new(article_params)
    @article.user = User.first

    if @article.save
      flash[:success] = 'Article was created !!! '
      redirect_to article_path(@article)
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @article.update(article_params)
      flash[:success] = 'Article was updated !!! '
      redirect_to article_path(@article)
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:danger] = 'Article was deleted'
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :description)
  end

  def get_article
    @article = Article.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

def index
	@users = User.all
end

  def new
    @user = User.new
  end

  def create
    @user = User.new(get_user_params)
    if @user.save
      flash[:success] = 'User was created !!! '
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(get_user_params)
      flash[:success] = 'User was updated !!! '
      redirect_to articles_path
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def get_user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "http://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt:user.username,class: "img-circle")
	end
end

app/views/articles/_form.html.erb
<%= render('shared/errors' , obj: @article)  %>
<div class="row">
	<div class="col-md-12">
		<%= form_for(@article, :html => {class: "form-horizontal" , role: "form" }) do |d| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= d.label :title%>
			</div>
			<div class="col-sm-8">
				<%= d.text_field :title , class: "form-control", placeholder: "Title of acrticle" , autofocus: true %>
			</div>
		</div>
		
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= d.label :description%>
			</div>
			<div class="col-sm-8">
				<%= d.text_area :description, class: "form-control", placeholder: "Body of acrticle", rows:10 %>
			</div>
		</div>
		
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4">
				<%= d.submit class: 'btn btn-primary btn-large'%>
			</div>
		</div> 
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			[ <%= link_to "Cancel request and return to article listing" , articles_path %> ]
		</div>
		
	</div>
</div>

app/views/articles/_index.html.erb
<div class="row">
	 <% articles.each do |article| %>
		<div class="box">
		 	<div class="well well-lg">
		 		<div class="article-title">
		 			 <%= link_to article.title, article_path(article) %> 
		 		</div>	 		
		 		<div class="article-body">
		 			 <%= truncate(article.description, length:100) %> 
		 			 <% if article.user %>
		 			 <div class="article-meta-details">
				 			 <small>
				 			 				<span> author:     <%= article.user.username %>                     </span>
				 			 				<span> created:    <%= time_ago_in_words(article.created_at) %> ago </span>
				 			 				<span> updated:    <%= time_ago_in_words(article.updated_at) %> ago </span>
				 			 </small>
		 			 </div>
		 			 <% end %>
		 		</div>	

		 		<div class="btn-holder ">
					<%= link_to "Edit" ,  edit_article_path(article) , class: "btn btn-xs btn-primary" %> 
					<%= link_to "Delete" , articles_path(article) , method: :delete, data: {confirm: "Are you shure" } ,class: "btn btn-xs btn-danger" %>
				</div> 		
		 		
		 </div>
	</div>
<% end %>
</div>

app/views/articles/edit.html.erb
<h1 style=" text-align: center; margin-bottom: 30px"> Edit existing article</h1>

<%= render('form') %>

app/views/articles/index.html.erb
<h1 style="margin-bottom: 30px" >All articles</h1>
 
<%= render("index", articles: @articles )%>

app/views/articles/new.html.erb
<h1 style=" text-align: center; margin-bottom: 30px"> Create an Article</h1>

<%= render('form') %> 

app/views/articles/show.html.erb
<h2 style="text-align: center; margin-bottom: 40px;"> <%= @article.title %></h2>

<div class="well col-xs-8 col-xs-offset-2">
	<h4 ><strong>Description:</strong> </h4>
	<hr>
	<%= simple_format(@article.description) %>


<div class="btn-holder">
	<%= link_to "Edit" ,  edit_article_path(@article) , class: "btn btn-xs btn-primary" %> 
	<%= link_to "Back" ,  articles_path , class: "btn btn-xs btn-success" %>
	<%= link_to "Delete" , articles_path(@article) , method: :delete, data: {confirm: "Are you shure" } ,class: "btn btn-xs btn-danger" %>
</div>

</div>

app/views/layouts/_footer.html.erb
<div class="container">
	<footer class="footer">
		<small>Copyright &copy; by Nudelman Alex - Rails Course</small>
	</footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
	<div class="col-xs-10 col-xs-offset-1">
		<% flash.each do |name, msg| %> 
			<div class='alert alert-<%="#{name}" %>'> 
				<a href="#" class="close" data-dismiss="alert"> &times;</a>
				<%= content_tag :div , msg, :id => "flash_#{name}" if msg.is_a?(String)  %>

			</div>
		<% end %> 
	</div>	
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- <a class="navbar-brand logo" href="#">MyBlog</a> -->
      <%= link_to  "MyBlog" , root_path , class:"navbar-brand logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Articles", articles_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li> <%= link_to "New Article",  new_article_path %> </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>	
<%= render 'layouts/messages' %>	
<div class="container">
<%= yield %>	
</div>

<%= render 'layouts/footer'  %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

app/views/pages/home.html.erb
<div class="jumbotron home">
  <h1 class="logo" >Welcome</h1>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
  tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
  quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
  consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
  cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
  proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
  <p class="btn-holder">
  	
  	 	<%= link_to("Sing-up", "#" , class: "btn btn-primary btn-lg") %>
  	 	<%= link_to("About", about_path , class: "btn btn-primary btn-lg") %>
  	 
  </p>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
<div class="row">
	<div class="col-xs-8 col-xs-offset-2">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h2 class="panel-title">
				<%= pluralize(obj.errors.count, "error") %>
				fix to be:
				</h2>
				<div class="panel-body">
					<ul>
						<% obj.errors.full_messages.each do |msg| %>
						<li><%= msg%></li>
						<% end %>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>

<% end %>

app/views/users/_form.html.erb
<%= render('shared/errors' , obj: @user)  %>

<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_for(@user, :html => {class: "form-horizontal" , role: "form" }) do |d| %>
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= d.label :username %>
			</div>
			<div class="col-sm-8">
				<%= d.text_field :username , class: "form-control", placeholder: "Please enter username" , autofocus: true %>
			</div>
		</div>
		
		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= d.label :email%>
			</div>
			<div class="col-sm-8">
				<%= d.email_field :email, class: "form-control", placeholder: "Enter Email", rows:10 %>
			</div>
		</div>

		<div class="form-group">
			<div class="control-label col-sm-2">
				<%= d.label :password%>
			</div>
			<div class="col-sm-8">
				<%= d.password_field :password, class: "form-control", placeholder: "Enter password", rows:10 %>
			</div>
		</div>
		
		<div class="form-group">
			<div class="col-sm-offset-2 col-sm-4">
				<%= d.submit @user.new_record? ? "Sign up" : "Update" , class: 'btn btn-primary btn-large'%>
			</div>
		</div> 
		<% end %>
		<div class="col-xs-4 col-xs-offset-4">
			
		</div>
		
	</div>
</div>

app/views/users/_user.html.erb
<div class="box">
	<div class="row">
		
		<div class="card hovercard ">
			
			<div class="avatar">
				<img alt="" src=<%= image_path('profile.png')%> width="100px" height="100px">
			</div>
			<div class="info">
				<div class="desc"><i class="glyphicon glyphicon-user"> Name: </i>  <%= link_to user.username, user_path(user)%></div>
				<div class="desc"><i class="glyphicon glyphicon-envelope"> Mail: </i> <%= user.email%></div>
				<div class="desc"><i class="glyphicon glyphicon-check"> Created: </i> <%= user.created_at.strftime("%B %d, %Y") %>
					<div class="desc"><i class="glyphicon glyphicon-pencil"> Articles: </i> <%= pluralize(user.articles.count, "articles")%></div>
				</div>
			</div>
			
		</div>
		
	</div>
</div>

app/views/users/edit.html.erb
<%= render('shared/errors' , obj: @user)  %>
<h1 style=" text-align: center; margin-bottom: 30px"> Edit User</h1>
<%= render('form') %>

app/views/users/index.html.erb
<h1 style="margin-bottom: 30px" >All users</h1>
 
<div class="row">
	<div class="container">
		
	<% @users.each do |user| %>
		<%= render('user' , user: user )%>
	<% end %>

	</div>
</div>

app/views/users/new.html.erb
<%= render('shared/errors' , obj: @user)  %>
<h1 style=" text-align: center; margin-bottom: 30px"> New User</h1>
<%= render('form') %>

app/views/users/show.html.erb
<h1 style=" text-align: center; margin-bottom: 30px"> Welcome <%= @user.username %></h1>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="well well-sm">
                <div class="row">
                    <div class="col-sm-6 col-md-4">
                        <img src=<%= image_path('user-yoda.jpg') %>  alt="" class="img-rounded img-responsive" />
                    </div>
                    <div class="col-sm-6 col-md-8">
                        <h4><%= @user.username%></h4>
                        <small><cite title="Earth Planet"> Earth Planet <i class="glyphicon glyphicon-map-marker">
                        </i></cite></small>
                        <p>
                            <i class="glyphicon glyphicon-envelope"></i> <%= @user.email%>
                            <br />
                            <i class="glyphicon glyphicon-globe"></i> <a href="http://www.samanage.com">www.samanage.com</a>
                            <br />
                            <i class="glyphicon glyphicon-gift"></i> <%=@user.created_at.strftime("%B %d, %Y") %></p>
                        <!-- Split button -->
                  
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <h3>Articles by <%= @user.username%></h3>
        <hr>
        <div class="container">
            <%= render("articles/index", articles: @user.articles )%>
        </div>
    </div>
</div>